/*
 * (c) Copyright 2018 Palantir Technologies Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath 'com.palantir.baseline-error-prone:gradle-baseline-error-prone:0.8.0'
        classpath 'com.palantir.jakartapackagealignment:jakarta-package-alignment:0.6.0'
        classpath 'com.palantir.gradle.jdks:gradle-jdks:0.73.0'
        classpath 'com.palantir.gradle.jdkslatest:gradle-jdks-latest:0.25.0'
        classpath 'com.palantir.gradle.externalpublish:gradle-external-publish-plugin:1.27.0'
        classpath 'com.palantir.gradle.failure-reports:gradle-failure-reports:1.18.0'
        classpath 'org.revapi:gradle-revapi:1.8.0'
        classpath 'com.palantir.javaformat:gradle-palantir-java-format:2.85.0'
        classpath 'com.palantir.baseline:gradle-baseline-java:6.90.0'
        classpath 'com.palantir.gradle.gitversion:gradle-git-version:4.2.0'
        classpath 'com.palantir.gradle.idea-configuration:gradle-idea-configuration:0.8.0'
        classpath 'com.palantir.metricschema:gradle-metric-schema:0.39.0'
        classpath 'com.palantir.suppressible-error-prone:gradle-suppressible-error-prone:2.26.0'
        classpath 'com.palantir.gradle.conjure:gradle-conjure:5.64.0'
        classpath 'org.unbroken-dome.gradle-plugins:gradle-testsets-plugin:4.1.0'
    }
}

plugins {
id 'com.palantir.consistent-versions' version '3.8.0'
}

apply plugin: 'com.palantir.external-publish'
apply plugin: 'com.palantir.failure-reports'
apply plugin: 'com.palantir.baseline'
apply plugin: 'com.palantir.baseline-error-prone-root'
apply plugin: 'com.palantir.git-version'
apply plugin: 'com.palantir.jdks'
apply plugin: 'com.palantir.baseline-java-versions'
apply plugin: 'com.palantir.jdks.latest'

javaVersions {
    javaCompiler = 25
    libraryTarget = 17
    runtime = 25
}

version System.env.CIRCLE_TAG ?: gitVersion()

allprojects {
    apply plugin: 'com.palantir.java-format'
    apply plugin: 'com.palantir.jakarta-package-alignment'

    group 'com.palantir.dialogue'
    version rootProject.version

    repositories {
        mavenCentral() { metadataSources { mavenPom(); ignoreGradleMetadataRedirection() } }
    }
    configurations.all {
        resolutionStrategy.preferProjectModules()
    }
}

subprojects {
    apply plugin: 'java-library'

    tasks.withType(JavaCompile) {
        options.compilerArgs += ['-Werror']
    }

    plugins.withId('com.palantir.baseline-error-prone', {
        dependencies {
            errorprone 'com.uber.nullaway:nullaway'
        }

        tasks.withType(JavaCompile).configureEach(task -> {
            if (name.toLowerCase().contains("test")) {
                options.errorprone.disable('NullAway')
            } else {
                options.errorprone.option('NullAway:AnnotatedPackages', 'com.palantir,com.google.common')
                options.errorprone.option('NullAway:CheckOptionalEmptiness', 'true')
                // As of NullAway 0.12.11, JSpecify annotations require Java 22+
                // https://github.com/uber/NullAway/wiki/JSpecify-Support#supported-jdk-versions
                options.errorprone.option('NullAway:JSpecifyMode',
                        task.javaCompiler.map { it.metadata.languageVersion.asInt() >= 22 ? 'true' : 'false' })
            }
            // This project is performance sensitive
            options.errorprone.disable('PreferJavaTimeOverload')
        })
    })

    tasks.check.dependsOn checkImplicitDependencies, checkUnusedDependencies
    tasks.checkImplicitDependenciesTest.enabled = false // doesn't impact users
    tasks.checkUnusedDependenciesTest.enabled = false // doesn't impact users
}

jdks {
    daemonTarget = 21
}
